# Site settings
title:          glibbie's blog
description:    "A random collection of various thoughts"
url:            "https://glibbie.github.io"

# Author
author:
  name:         
  url:          https://glibbie.github.io
  email:        glibbieblog@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
